# Generated by Django 5.0 on 2023-12-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuusinhvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('student_id', models.CharField(max_length=10)),
            ],
        ),
    ]
